name: facial_recognition
description: >-
  App para contabilizar a presença de alunos em aula através do reconhecimento
  facial destes. App desenvolvido como projeto final para o bacharelado em
  Ciência da Computação.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.5.1
  logging: ^1.1.1
  camera: ^0.10.4
  google_mlkit_face_detection: ^0.5.0
  image: ^4.0.16
  tflite_flutter: ^0.10.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  requests: ^4.7.0
  sqlite3: ^1.11.2
  path: ^1.8.2
  crypto: ^3.0.3
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.22.0

flutter:
  uses-material-design: true
  assets:
    - assets\facenet512_00d21808fc7d.tflite
