name: facial_recognition
description: 'App para contabilizar a presença de alunos em aula através do
reconhecimento facial destes. App desenvolvido como projeto final para o
bacharelado em Ciência de  Computação.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
