name: facial_recognition
description: >-
  App para contabilizar a presença de alunos em aula através do reconhecimento
  facial destes. App desenvolvido como projeto final para o bacharelado em
  Ciência da Computação.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  logging: ^1.1.1
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.12.0
  image: ^4.0.16
  tflite_flutter: ^0.11.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  requests: ^4.7.0
  sqlite3: ^2.4.6
  path: ^1.8.2
  crypto: ^3.0.3
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.1
  file_picker: ^8.1.2
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.22.0

flutter:
  uses-material-design: true
  assets:
    - assets\facenet512_00d21808fc7d.tflite
    - assets\sqlStatements_v2.json
